// <auto-generated />
namespace DemoConectDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Altr_column_Studet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Altr_column_Studet));
        
        string IMigrationMetadata.Id
        {
            get { return "202109100915217_Altr_column_Studet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
