// <auto-generated />
namespace DemoConectDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Table_People_Children : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_People_Children));
        
        string IMigrationMetadata.Id
        {
            get { return "202111230722158_Table_People_Children"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
